---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: observability
spec:
  image: docker.io/otel/opentelemetry-collector-contrib:0.145.0
  mode: deployment
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    connectors:
      spanmetrics:
        namespace: gen_ai
        histogram:
          explicit:
            buckets: [1]
        dimensions:
          - name: service.name
          - name: gen_ai.evaluation.name
          - name: gen_ai.evaluation.score.label
          - name: gen_ai.evaluation.score.value
        metrics_flush_interval: 15s

    exporters:
      prometheus:
        endpoint: 0.0.0.0:8889

    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [spanmetrics]
        metrics:
          receivers: [spanmetrics]
          exporters: [prometheus]
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-collector
  namespace: observability
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-collector
  endpoints:
    - port: prometheus
      interval: 3s
