---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: story-app-1
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      automountServiceAccountToken: false
      serviceAccountName: supply-chain
      containers:
        - name: workload
          image: ghcr.io/thomasvitale/scaling-on-satisfaction:f59ceb9f63e5b07d3c003bd5479c088a5cea80b3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: STORY_THEME
              value: "MOON"
            - name: STORY_STYLE
              value: "DRY" # DRY or FUNNY
            - name: STORY_MODEL
              value: "SMALL"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.observability.svc.cluster.local:4318"
            - name: OTEL_LOGS_EXPORTER
              value: "none"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: MISTRAL_AI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mistral-ai
                  key: api-key
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: postgresql-story-app
                  key: jdbc-uri
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgresql-story-app
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-story-app
                  key: password
            - name: SPRING_SECURITY_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: admin-credentials
                  key: username
            - name: SPRING_SECURITY_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: admin-credentials
                  key: password
          livenessProbe:
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
            limits:
              memory: 1Gi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1001
            seccompProfile:
              type: RuntimeDefault
