apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: story-app-1
spec:
  template:
    metadata:
      labels:
        app: story-app-1b
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "1"
        instrumentation.opentelemetry.io/inject-nodejs: "otel-instrumentation"
    spec:
      automountServiceAccountToken: false
      serviceAccountName: supply-chain
      containers:
        - name: workload
          image: wiggitywhitney/story-app-1b:latest
          ports:
            - containerPort: 8080
          env:
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: anthropic
                  key: api-key
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1001
            seccompProfile:
              type: RuntimeDefault
