---
apiVersion: apps.kadras.io/v1alpha1
kind: StoryApp
metadata:
  name: story-app-1
spec:
  image: ghcr.io/thomasvitale/scaling-on-satisfaction:fe75708ff2f234ddebed32237d73c8d473ffae7c
  story:
    theme: MOON
    variant: A
