---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crossplane-storyapp-composed-resources
  labels:
    rbac.crossplane.io/aggregate-to-crossplane: "true"
rules:
  - apiGroups:
      - serving.knative.dev
    resources:
      - services
      - services/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - flagger.app
    resources:
      - canaries
      - canaries/status
      - metrictemplates
      - metrictemplates/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
