---
apiVersion: v1
kind: Namespace
metadata:
  name: flagger-system
  labels:
    toolkit.fluxcd.io/tenant: platform-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: flagger
  namespace: flagger-system
spec:
  interval: 1h
  url: oci://ghcr.io/fluxcd/charts
  type: oci
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flagger
  namespace: flagger-system
spec:
  interval: 1h
  releaseName: flagger
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: flagger
      version: 1.x
      interval: 6h
      sourceRef:
        kind: HelmRepository
        name: flagger
      verify:
        provider: cosign 
  values:
    nodeSelector:
      kubernetes.io/os: linux
    meshProvider: knative
    metricsServer: http://flagger-prometheus:9090
    prometheus:
      install: true
      retention: 2h    
